#!/bin/bash

# Removes the script from /src
# Removes the log from /logs
# Removes the config from /config

[[ $# = 1 ]] || { echo Please provide script name to delete; exit 1; }

file_path="$(pwd)/"
script_name="${1}"
script_path="${file_path}src/${script_name}"

[[ -e ${script_path} ]] && rm ${script_path} && echo ${script_path} removed

log_path="${file_path}logs/${script_name}.log"
config_path="${file_path}config/${script_name}.config"
test_path="${file_path}test/test_${script_name}"
header_path="${file_path}header/${script_name}.h"

[[ -e ${log_path} ]] && rm ${log_path} && echo ${log_path} removed
[[ -e ${config_path} ]] && rm ${config_path} && echo ${config_path} removed
[[ -e ${test_path} ]] && rm ${test_path} && echo ${test_path} removed
[[ -e ${header_path} ]] && rm ${header_path} && echo ${header_path} removed
